[package]
name = "featureselect"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
plotters = "0.3.7"
pyo3 = { version = "0.23.4", features = ["auto-initialize"] }
rand = "0.8.5"
smartcore = "0.4.0"

